### ISSUE TITLE
[SR-16042] DocC generates index.html that doesn't use --hosting-base-path

### ISSUE THREAD

**Issue by jtbandes** [apple/swift-docc#170]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16042      |
   |Radar             | None         |
   |Original Reporter | @jtbandes      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)

``` java
{
  "object": {
    "pins": [
      {
        "package": "SwiftDocCPlugin",
        "repositoryURL": "https://github.com/apple/swift-docc-plugin",
        "state": {
          "branch": null,
          "revision": "3303b164430d9a7055ba484c8ead67a52f7b74f6",
          "version": "1.0.0"
        }
      }
    ]
  },
  "version": 1
}
 
```

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 68de8a51863bf493c17466efcfa3d0c5

  </details>

**Issue Description:**

I am attempting to use DocC to generate documentation that I will host on GitHub Pages: <https://github.com/foxglove/mcap/pull/325>

When I run:

``` java
swift package \
  --allow-writing-to-directory __docs__ \
  generate-documentation --target mcap \
  --output-path __docs__/swift \
  --disable-indexing \
  --transform-for-static-hosting \
  --hosting-base-path mcap/swift 
```

Then the generated file at `docs/swift/documentation/mcap/index.html` correctly includes `var baseUrl = "/mcap/swift/";` and resource URLs are prefixed with this base path. And this page works: <https://foxglove.github.io/mcap/swift/documentation/mcap> 

However, it **also** produces a file at `docs/swift/index.html` which contains **`var baseUrl = "/";`**, and resource URLs starting with `/css` or `/js`, which is wrong. And this page is broken: <https://foxglove.github.io/mcap/swift>

This index.html file should use the same baseUrl that I provided on the command line.

**Comment by ethan-kusters** [comment]
Thanks for filing this @jtbandes! I'll resolve this as part of the refactor in #166.
