### ISSUE TITLE
[SR-15982] SymbolKit crashes when encoding unknown mixins

### ISSUE THREAD

**Issue by franklinsch** [apple/swift-docc#174]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15982      |
   |Radar             | rdar://problem/90348996         |
   |Original Reporter | @franklinsch      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7a780d28224eef5a62504852074094c5

  </details>

**Issue Description:**

SymbolKit *decodes* unknown Symbol mixins just fine by adding them to `Symbol.mixins`, but {{fatalError}}s when *encoding* unknown mixins: <https://github.com/apple/swift-docc-symbolkit/blob/main/Sources/SymbolKit/SymbolGraph/Symbol/Symbol.swift#L180.>

For example, when decoding a symbol graph from the Swift compiler (which includes the `location` mixin) and encoding it back, SymbolKit crashes.

We should make SymbolKit encode unknown mixins.

**Comment by theMomax** [comment]
This issue was solved by apple/swift-docc-symbolkit#39.

**Comment by Kyle-Ye** [comment]
[apple/swift-docc-symbolfix#39](https://github.com/apple/swift-docc-symbolkit/pull/39) fix the issue in the upstream.
#369 update the SymbolKit dependency commit in swift-docc.
