### ISSUE TITLE
[SR-15867] Docc Overviews and Links don't work with Package that uses tools-version less than 5.5

### ISSUE THREAD

**Issue by fabianfett** [apple/swift-docc#183]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15867      |
   |Radar             | None         |
   |Original Reporter | @fabianfett      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Could reproduce in nightly main, 5.6 on macOS and Linux.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4ab050b4888cf3bcdf484a612fbce89b

  </details>

**Issue Description:**

I noticed that the Docc export off overview files does not work, if the packages tools-version is less than Swift 5.5. I could reproduce this while trying to add docc to a number of open source packages (SwiftNIO, AsyncHTTPClient, PostgresNIO, AWSLambdaRuntime).

One can work around this issue in two ways:

1\. Create a Package@swift-5.5.swift that matches the existing Package.swift except for the required tools-version  
2. Update the Package.swift in CI, before creating the docc bundle:

**Comment by Kyle-Ye** [comment]
Expected behavior. Close
