### ISSUE TITLE
[SR-15754] Override merge behaviour removes all Xcode popover documentation

### ISSUE THREAD

**Issue by karwa** [apple/swift-docc#189]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15754      |
   |Radar             | None         |
   |Original Reporter | @karwa      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964429-3b9b71d8-be10-48aa-9968-48ba9ec156e0.gz)

      
<details>
  <summary>Environment</summary>

macOS 11.6, Xcode 13.2.1 (13C100)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ee66e5044a4c31ce0a974d83ef42f904

  </details>

**Issue Description:**

In my package, I have a type which is documented via a markdown extension doc. This looks great in the documentation browser, but I also want to provide great documentation in the Xcode alt+click popover.

Currently, the default appears to append the source docs with the extension docs, meaning I need to limit the popover docs to just the first line:

Code:

<img src="image-2022-01-19-22-35-54-009.png" width="427" height="70" />

Popover:

<img src="image-2022-01-19-22-36-23-970.png" width="468" height="199" />

Documentation browser (notice the summary up top comes from the source docs):

<img src="image-2022-01-19-22-37-06-604.png" width="429" height="290" />

 

---

 

Now, if I extend the source docs with a longer (yet still abbreviated) summary, I get a better popover experience, but the documentation browser duplicates it, with 2 overview sections:

Popover:

<img src="image-2022-01-19-22-39-38-785.png" width="372" height="448" />

Documentation browser:

<img src="image-2022-01-19-22-43-33-991.png" width="578" height="545" />

 

---

 

Now, if I add specify the "override" merge behaviour in the markdown document, I can remove the duplicated content in the documentation browser, but now get absolutely no popover documentation at all, despite there obviously being documentation which you can see in the background.

<img src="image-2022-01-19-22-49-07-344.png" width="487" height="376" />

 

This means I'm not able to provide a great popover and documentation browser experience simultaneously 🙁

**Comment by d-ronnqvist** [comment]
AFAICT this isn't an issue in Xcode 15. 

Regardless, issues about Xcode specific features are out of scope for this repo. For that, please file a [Feedback](http://feedbackassistant.apple.com) instead.
