### ISSUE TITLE
[SR-15585] Invalid task group list items do not have source locations

### ISSUE THREAD

**Issue by karwa** [apple/swift-docc#195]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15585      |
   |Radar             | rdar://problem/89641499         |
   |Original Reporter | @karwa      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift-DocC 92f7fe11da0cf357e8e9d38aab835055c4c1aa5b

Also present in the Xcode 13.1 build

macOS 11.6

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9c2a4789ba12c4f99e093155320236fb

  </details>

**Issue Description:**

If there is a non-link item in a "See Also" list or Topics list in a Swift source file, DocC will emit a warning: "Only links are allowed in task group list items" without a source location.

This makes locating the cause of the warning incredibly difficult. The only way I was able to discover where these things were coming from is by building my own version of DocC with a bunch of "dump()" calls thrown around.

This revealed that DocumentCurator was unable to find a document location for the node reference here: <https://github.com/apple/swift-docc/blob/d94139a5e64e9ecf158214b1cded2a2880fc1b02/Sources/SwiftDocC/Infrastructure/DocumentationCurator.swift#L176>

 

Steps to reproduce:

Add an item to a "See Also" list or "Topics" list which is just plain text (not a link), and build documentation. DocC will emit a warning with no location.

``` java
/// A thing
///
/// ## Topics
///
/// ### Things about Things
///
/// - bar
///
struct Foo {
}
```

**Comment by groue** [comment]
Thanks for mentioning the warning text, so that I could perform a web search and find this issue 👍 

The obscure warning is still there in Xcode 14.3 (14E222b).

**Comment by d-ronnqvist** [comment]
I believe that this was fixed by https://github.com/apple/swift-docc/pull/753
