### ISSUE TITLE
[SR-15407] DocC (wrongly) renders actors as classes

### ISSUE THREAD

**Issue by ktoso** [apple/swift-docc#212]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15407      |
   |Radar             | rdar://84751310         |
   |Original Reporter | @ktoso      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964349-af790ba0-c25a-43a9-a902-59c3bf815184.gz)

      
<details>
  <summary>Environment</summary>

Nightly \`main\` toolchain from October 27th

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Bug        |
   |Assignee          | @QuietMisdreavus      |
   |Priority          | Medium      |

   

   md5: 314cf0c884190d9ab14edc3fb2ab9753

  </details>

**Issue Description:**

Summary:  
Actors are listed as classes under the Classes: section. This is very confusing, they should be listed as their own category as they are stand alone nominal types.

Steps To Reproduce:  
1. Declare an actor `public actor NEIN {`}

Results:  
Actor shows up under classes as `class NEIN` which is misleading.

Expected:  
Should get their own section.

Extra:  
And **distributed** actors should get their own section as well, perhaps under actors?

**Comment by FranzBusch** [comment]
+1 just ran into this myself and found it pretty confusing

**Comment by akbashev** [comment]
+ 1 
Also just noticed that, a bit misleading when working with actors.

**Comment by heckj** [comment]
I'm taking a stab at fixing this per @QuietMisdreavus guidelines. Feedback _very_ welcome.
