### ISSUE TITLE
Better handling for invalid Info.plist files

### ISSUE THREAD

**Issue by franklinsch** [apple/swift-docc#259]
When building documentation for a catalog that contains an invalid `Info.plist` file, the error message `docc` outputs is not user-friendly:

```
$ docc convert IncompleteInfoPlist.docc

Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not a valid property list.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Value missing for key inside <dict> at line 26" UserInfo={NSDebugDescription=Value missing for key inside <dict> at line 26, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Malformed data byte group at line 1; invalid hex" UserInfo={NSDebugDescription=Malformed data byte group at line 1; invalid hex}})))
```

[IncompleteInfoPlist.docc.zip](https://github.com/apple/swift-docc/files/8714618/IncompleteInfoPlist.docc.zip)

We should display a more actionable user-facing diagnostic.

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Swift-DocC Version Information

**Swift-DocC version:** `5.7`, `main`

Radar: rdar://93376709

**Comment by Kyle-Ye** [comment]
Close by #267
