### ISSUE TITLE
Unexpected output path when generating docs for scheme "ParseSwift (iOS)"

### ISSUE THREAD

**Issue by finestructure** [apple/swift-docc#269]
When generating docs in the Swift Package Index for an iOS package, we're running the following set of commands:

```
git clone https://github.com/parse-community/Parse-Swift.git
cd Parse-Swift

env DEVELOPER_DIR="/Applications/Xcode-13.3.0.app" xcrun xcodebuild -derivedDataPath "$PWD/.derivedData" docbuild -scheme "ParseSwift (iOS)" -destination 'generic/platform=ios'

mkdir -p .docs/parse-community/Parse-Swift

env DEVELOPER_DIR="/Applications/Xcode-13.3.0.app" xcrun docc process-archive transform-for-static-hosting $(find "$PWD/.derivedData" -type d -name "*.doccarchive") --output-path ".docs/parse-community/Parse-Swift/main" --hosting-base-path "parse-community/Parse-Swift/main"
```

The output path we end up with here is:

```
❯ ls .docs/parse-community/Parse-Swift/main/documentation/
parseswift/
```

The problem is that we're trying to derive the hosting URL from the scheme the users have set ("ParseSwift (iOS)"), which we _thought_ was just going to be `scheme.lowercased()`, i.e. `parseswift (ios)`. It appears that it's also stripping the ` (iOS)` part.

The issue – if it is actually an issue – seems to the the output of the `docbuild` command. We are discovering it via the `find "$PWD/.derivedData" -type d -name "*.doccarchive"` and if I run this it results in:

```
❯ find ".derivedData" -type d -name "*.doccarchive"
.derivedData/Build/Products/Debug-iphoneos/ParseSwift.doccarchive
```

I'm guessing it's because `ParseSwift` is the actual framework/product/module name and this is what the archive is named after.

I think this is tripping us up when using `xcodebuild` to generate docs, because in Xcode you can end up with a scheme name that's disconnected from a product/module name whereas when building with `swift package generate-documentation --target` you can't really end up in that situation.

I'm pretty sure we can find a way to work around for this without deriving the resulting URL path ourselves but I'm raising this issue here as requested by @franklinsch in https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1770 just in case this is actually unintended behaviour.

**Comment by finestructure** [comment]
It does, thank you! The only thing that's a bit odd is that the project doesn't have a target `ParseSwift`:

<img width="185" alt="CleanShot 2022-05-31 at 14 23 21@2x" src="https://user-images.githubusercontent.com/65520/171172417-0aadc378-9fb7-47b7-9429-7733ab73a127.png">

So I'm guessing it must be the product that determines the docarchive's name? I was exploring this because I was hoping that I could introduce a temporary workaround by using `xcodebuild`'s `-target` parameter and changing the requested documentation target's name to `ParseSwift`.

```
❯ xcodebuild docbuild -target "ParseSwift" -destination 'generic/platform=ios'
2022-05-31 14:22:45.902 xcodebuild[38458:13144183] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-31 14:22:45.902 xcodebuild[38458:13144183] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode-13.4.0.app/Contents/Developer/usr/bin/xcodebuild docbuild -target ParseSwift -destination generic/platform=ios

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: The project 'ParseSwift.xcodeproj' does not contain a target named 'ParseSwift'.
```

Anyway, please feel free to close this, it seems like it's on us to adjust our assumptions!

**Comment by franklinsch** [comment]
I see, the DocC archive is be named after the target's `PRODUCT_NAME` ("Product Name" in build settings) I believe (@d-ronnqvist can confirm), which is not the name value you pass in the `-target` invocation.
