### ISSUE TITLE
Support Python3 build-script-helper.py 

### ISSUE THREAD

**Issue by shahmishal** [apple/swift-docc#272]
swift-docc build system script does not support python3, which is required to build on Ubuntu 22.04

```
+ /home/build-user/swift-docc/build-script-helper.py build --toolchain /home/build-user/swift-nightly-install/usr --configuration release --build-dir /home/build-user/build/buildbot_linux/unified-swiftpm-build-linux-x86_64 --multiroot-data-file /home/build-user/swift/utils/build_swift/resources/SwiftPM-Unified-Build.xcworkspace --update
/usr/bin/env: ‘python’: No such file or directory
```

https://ci.swift.org/job/oss-swift-package-ubuntu-22_04/116/console

**Comment by ethan-kusters** [comment]
I spoke with @shahmishal offline and the Swift project doesn't support `python2` on any OS so we should use this issue to fully migrate to `python3`. We don't need to maintain backwards compatibility.
