### ISSUE TITLE
Allow customize Add Document template

### ISSUE THREAD

**Issue by ErazerControl** [apple/swift-docc#315]
#### Description:
Because Docc supports multiline documentation comments, as described in the official doc
> DocC also supports multiline documentation comments. Begin a comment with a forward slash and two asterisks (/**), and terminate it with an asterisk and a forward slash (*/). 

How can I generate this style(/** /) template when I click add document? 

Now it seems to only generate three forward slash(///).

<img width="708" alt="image" src="https://user-images.githubusercontent.com/107595588/174740380-fc387852-f31d-4b89-9a51-e362a43b9aad.png">

#### Motivation:

Our team thinks /** style is more beautiful than ///. So hopefully DocC can allow custom templates of adding document.

#### Importance:
This is more flexible for developers.

#### Alternatives Considered

I tried to add Code Snippet, but it does not generate the name of parameters automatically. It's so sad.

**Comment by ethan-kusters** [comment]
Hi @ErazerControl! Thanks for bringing this up. Since this is an Xcode issue we'll be unable to track its resolution here. Would you mind [filing a Feedback](https://feedbackassistant.apple.com/) and posting the number here? That will allow the right folks on the Xcode team to track the issue.
