### ISSUE TITLE
The default 8000 port may conflict with existing local web server ports.

### ISSUE THREAD

**Issue by ShikiSuen** [apple/swift-docc#371]
### Feature Name

Change the default web port from 8000 to something else.

### Description

The default 8000 port may conflict with existing local web server ports.
Maybe there are other ports considerable like 114, 514, 1919, 810, 114514, etc.

### Importance

The default 8000 port may conflict with existing local web server ports.

**Comment by amartini51** [comment]
I suggest we should use port 8080.

The [IANA registry of port numbers][ports] lists port 80 as "World Wide Web HTTP" and port 8080 as "HTTP Alternate".  Port 8000 is registered for the "iRDMI" protocol.

[ports]: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http
