### ISSUE TITLE
Link resolution fail warnings in comment section

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-docc#377]
### Description

Currently, when we try to build swift-book's docc documention, it will give us a lot of warnings.

https://github.com/apple/swift-book/issues/9

Some diagnostic is useful and is tracked to Github issues waiting to be fixed.

However some diagnostic seems useless and IMO should not emit such as "Link resolution fail warnings" in comment section.

I think swift-docc should not emit such diagnostic if the link is from the comment section or add a flag to silence such diagnostic.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/43724855/189511008-7a070f68-a65d-4522-b29b-f6bf6e173b78.png">

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

**Comment by Kyle-Ye** [comment]
Building documentation without `--additional-symbol-graph-dir xx` seems could solve the problem.

And actually, for the TSPL package, the symbol graph is just empty so we could just omit this parameter to fix the problem in a script or CLI env.

But if we are in the Xcode environment and run "build documentation" in Xcode, it will automatically add this flag and thus causing the above unwanted diagnostics.

**Comment by franklinsch** [comment]
Thanks for filing this! Totally agree that these diagnostics shouldn't be emitted in the body of Comment directives. It should be treated as plain text.
