### ISSUE TITLE
DocC emits error for topic section missing topic group heading and ignores anonymous curation

### ISSUE THREAD

**Issue by ethan-kusters** [apple/swift-docc#404]
### Description

Swift-DocC’s support for anonymous topic sections (#393) doesn’t seem to work for article-only catalogs. 

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expect to be able to write topic groups with no topic headings in an article-only catalog that uses `@TechnologyRoot`.

### Actual behavior

I see the following warnings:

```
/Users/ekusters/Downloads/AnonymousTopicTest.docc/Article1.md:5:1: warning: Missing required subheading for Topics section.
A Topics section requires at least one topic, represented by a level-3 subheading. A Topics section without topics won’t render any content.”
/Users/ekusters/Downloads/AnonymousTopicTest.docc/Test.md:7:1: warning: Missing required subheading for Topics section.
A Topics section requires at least one topic, represented by a level-3 subheading. A Topics section without topics won’t render any content.”
```

And the built Archive does not include my curations.

### Steps To Reproduce

1. Open the [attached DocC catalog](https://github.com/apple/swift-docc/files/9758348/AnonymousTopicTest.docc.zip)

2. `docc preview`

### Swift-DocC Version Information

61100a4

### Related Issues

- rdar://100994549

**Comment by dobromir-hristov** [comment]
Noticed this one today while trying to remove groupMarkers from the navigator. Removed the H3 under Topics and It removed all those items from the page Topics and from the Nav hierarchy as well.
