### ISSUE TITLE
Provide Docker Container for DocC

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-docc#426]
### Feature Name

DocC Docker Container

### Description

It would be great to have a Docker Container that contains a prebuilt binary for DocC. This would allow the container to be cached and the image to be used in CI runs without needing to clone and build all of DocC, and then source code before documentation can be generated 

### Motivation

Vapor is transitioning our API Docs to DocC. Every push to `main` will trigger a build for that package. Currently every build also needs to build DocC before we can build the source, which can take a significant amount of time. If we were able to set something like `swiftlang:swift-5.7-docc` as the CI container image, this would significantly speed up our documentation generation time

### Importance

Not massively important - DocC can be built manually for now

### Alternatives Considered

Provide a binary that can be downloaded or integrate into the Swift toolchain - these would probably require extra work (and/or evolution pitches). A long term goal of `swift docs generate` a la Rust would be great though

**Comment by ethan-kusters** [comment]
Hi @0xTim!

Swift-DocC integrated with the Swift toolchain as part of its initial open source release: https://forums.swift.org/t/swift-docc-is-now-included-in-swift-toolchains-for-both-macos-and-linux/53284.

So it should already be available in all of the Swift.org Linux Docker contains from version 5.6 onward.

> A long term goal of swift docs generate a la Rust would be great though

I agree this would be great. Today the closest you can get is adding the [Swift-DocC plugin](https://apple.github.io/swift-docc-plugin/documentation/swiftdoccplugin/) which will orchestrate the `docc` build for you using the `docc` included in the Swift toolchain when you run `swift package generate-documentation`.

**Comment by 0xTim** [comment]
Ah I didn't realise! I can confirm that `docc` is available as a command to call in `swift:5.7` Docker images. We've uncovered a couple of issues with the toolchain in Docker but I'll open separate issues for these
