### ISSUE TITLE
DocC Toolchain provided with Swift not generating documentation

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-docc#428]
### Description

When using `docc` from the Swift toolchain on Linux (tested on `swift:5.7` Docker images and macOS) to create docs for static hosting we're finding that whilst it generates the top level directory with the images, JS, CSS etc, it's not generating a `documentation` directory with the documentation in.

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Running

```bash
docc convert packages/postgres-nio/Sources/PostgresNIO/Docs.docc/ --fallback-display-name PostgresNIO --fallback-bundle-identifier nio.postgres --fallback-bundle-version 1.0.0 --additional-symbol-graph-dir packages/postgres-nio/.build/postgres-nio-symbol-graphs --transform-for-static-hosting --output-path public/postgres-nio --hosting-base-path /postgres-nio
```
Should generate a documentation package in `public/postgres-nio/documentation` that can be uploaded for static hosting

### Actual behavior

The generated files in `public/postgres-nio` are:

```
drwxr-xr-x  7 root root   224 Nov 17 14:05 css
-rw-r--r--  1 root root 12562 Nov 17 14:05 developer-og-twitter.jpg
-rw-r--r--  1 root root 12856 Nov 17 14:05 developer-og.jpg
drwxr-xr-x  2 root root    64 Nov 17 14:05 downloads
-rw-r--r--  1 root root 15406 Nov 17 14:05 favicon.ico
-rw-r--r--  1 root root  1466 Nov 17 14:05 favicon.svg
drwxr-xr-x  2 root root    64 Nov 17 14:05 images
drwxr-xr-x  6 root root   192 Nov 17 14:05 img
drwxr-xr-x  3 root root    96 Nov 17 14:05 index
-rw-r--r--  1 root root  4235 Nov 17 14:05 index.html
drwxr-xr-x 31 root root   992 Nov 17 14:05 js
-rw-rw-rw-  1 root root   117 Nov 17 14:05 metadata.json
-rw-r--r--  1 root root  1089 Nov 17 14:05 theme-settings.json
drwxr-xr-x  2 root root    64 Nov 17 14:05 videos
```

**Note:** no `documentation` directory

### Steps To Reproduce

```bash
git clone https://github.com/vapor/api-docs.git && cd api-docs && git checkout toolchain-docc && docker run --rm -it --entrypoint bash -v $(pwd):/root swift:5.7
cd /root && ./generate-api-docs.swift
```

This will clone PostgresNIO, build the docs and then run the above command

### Swift-DocC Version Information

5.7.1

### Swift Compiler Version Information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

Swift version 5.7.1 (swift-5.7.1-RELEASE)
Target: aarch64-unknown-linux-gnu
```

**Comment by Kyle-Ye** [comment]
> Steps To Reproduce
> ```shell
> git clone https://github.com/vapor/api-docs.git && cd api-docs && git checkout toolchain-docc && docker run --rm -it --entrypoint bash -v $(pwd):/root swift:5.7
> cd /root && ./generate-api-docs.swift
> ```

Hi, Tim. Does the issue get fixed? Looks like there is no toolchain-docc branch in api-docs anymore thus I can't reproduce it.
cc @0xTim

**Comment by 0xTim** [comment]
Yes this can be closed - it was an issue with our symbol directory
