### ISSUE TITLE
Combine multiple code language for export 

### ISSUE THREAD

**Issue by oilladaMELI** [apple/swift-docc#442]
### Feature Name

Combine multiple code language for export 

### Description

We need to export Swift and Objc documentation for a single file to host in our webpage.

### Motivation

We have a lot of libraries with both swift and objective-c code, we need to be able to export both language documentation in a single file to host in our webpage.

**Comment by d-ronnqvist** [comment]
This should already be working if DocC gets the symbol information for both Swift and Objective-C together. 

Can you provide an example of the inputs that you are passing to `docc`?

**Comment by d-ronnqvist** [comment]
Combined Swift and Objective-C documentation has been supported since before this issue was opened and this issue doesn't provide additional details on how to reproduce the issue.

Feel free to reopen this issue with additional details.
