### ISSUE TITLE
Clearly indicate when a build resulted in no pages

### ISSUE THREAD

**Issue by d-ronnqvist** [apple/swift-docc#553]
### Feature Name

Indicate when a build resulted in no pages

### Description

Today when a documentation build results in an archive with no pages (an empty data directory) there is no clear indication that of this. This can lead to confusion for developers. The behavior when previewing documentation is more confusing because DocC outputs a localhost URL where the developer can preview the documentation but there is nothing to preview there.

This behavior goes back to workflows where a developer can create an empty documentation catalog, start a preview of that documentation—which starts monitoring the files for changes—and then start writing markup and refresh the preview to see the latest changes. Most of this workflow is good to keep, but I feel that the specific behavior where the developer can start previewing no content is causing more confusion than it adds value. This empty catalog workflow is only relevant when staring a new documentation project without symbols. 

I can see a few different solutions to this problem with different amounts of breaking behavior.

1. Raise a warning if a documentation build (`docc convert`) didn't result in any pages
2. Don't output a .doccarchive if the documentation build (`docc convert`) didn't result in any pages
3. Exit with an error code if the documentation build (`docc convert`) didn't result in any pages
4. Silently do nothing for `docc convert` but exit with an error code if `docc preview` doesn't have any pages to preview.

I'm not sure what the right solution is here. My main concern for solution 3 is that in some use cases when building documentation for targets with dependencies it might be too disruptive to fail the overall build if one of the dependencies didn't output documentation.  

### Motivation

The behavior that empty builds look like they are working is causing confusion. Most of the time empty output is unexpected. 

### Importance

This is fairly low priority but it does smooth over one rough edge of the documentation building experience and help some developers spot specific issues sooner. 

### Alternatives Considered

I can imagine at least 4 different solutions (and various combinations of them) as possible alternatives to consider for this issue. These alternatives are outlined in the description.

------

This issue is also tracked as <rdar://93371988>

**Comment by d-ronnqvist** [comment]
This is kind of a good first issue. The coding changes are fairly small but there's a good opportunity here for a developer to think about the tradeoffs between various solutions and have a discussion in the Swift Forums to find the right solution. 

Discussing the tradeoffs in the Swift Forums will require a new developer to familiarize themselves with behaviors of `docc convert` and `docc preview`.

**Comment by sofiaromorales** [comment]
Hi @d-ronnqvist, I would like to work on this. Since this issue is quite old, do you now if there's been any work or discussion related to it that I should be aware of?

**Comment by d-ronnqvist** [comment]
Hi. as far as I’m aware there has been no further work or discussion on this issue.

**Comment by sofiaromorales** [comment]
Hi @d-ronnqvist. I agree that this solution could use a combination of the different options you listed. My most immediate proposition when either previewing or converting documentation that will end up with no pages is to raise a warning, and, in the case of `docc convert`, not emit a doccarchive for those documentations that resulted in no pages. So a combination of solutions 1 and 2. This can also be discussed on the forums with the rest of the community. I’ll open a discussion there to talk about this.

In the meantime, could you point me to the files inside Swift-DocC that I should keep an eye on for this implementation? My best guess is that I have to check that the `topic` dictionary inside `renderContext.store` has data in it.

```swift
// DocumentationConverter.swift
mutating public func convert<OutputConsumer: ConvertOutputConsumer>(
        outputConsumer: OutputConsumer
    ) throws -> (analysisProblems: [Problem], conversionProblems: [Problem]) {
        ...
        // Precompute the render context
        let renderContext = RenderContext(documentationContext: context, bundle: bundle)

       // Emit warning if renderContext.store.topics is empty
       ...
}
```

**Comment by d-ronnqvist** [comment]
There are a couple of different places where you could check if the build doesn't result in any pages.

The only place that I'm aware of that checks this today is in `PreviewAction.printPreviewAddresses(base:)` which prints the base preview paths of all the top-level pages (module pages, technology roots, and tutorials). The preview actions gets these paths from the documentation context as
```swift
previewPaths = try convertAction.context.previewPaths()
```
which in turn checks the context's `rootModules` and `rootTechnologies`. This works because individual symbols and articles only get a page if they belong to some module or technology. 

We wouldn't want to tie this diagnostic to the code that prints the preview addresses but the underlying check could be the same.

One thing to consider is that the preview action internally uses a convert action, so if the two should behave differently then the convert action likely needs some new configuration that the preview action can control.
