### ISSUE TITLE
Empty `.docc` bundle causes "An unknown error occurred" error message

### ISSUE THREAD

**Issue by MaxDesiatov** [apple/swift-docc#559]
### Description

A confusing error message is displayed for an empty `.docc` bundle. It's unclear what exactly went wrong as no details are provided by DocC.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

An actionable error message is displayed during `docc preview` execution that clarifies that empty bundles can't be previewed, or a placeholder page displayed in the browser. Either of these should provide actionable steps a user could take to author content for the newly created bundle.

### Actual behavior

 "An unknown error occurred" error message is displayed in the browser, no error message is displayed in the terminal.

### Steps To Reproduce

Run first two steps in the terminal:
1. `mkdir foo.docc`
2. `xcrun docc preview foo.docc`
3. Open  http://localhost:8080/ in the browser

Also reproducible for a bundle that doesn't have `Info.plist` in it.

### Swift-DocC Version Information

Swift 5.9 snapshots or 1d300e782de6ec834f29ff4c4832f25fcd82ae8a commit in the `main` branch of `swift-docc`

### Swift Compiler Version Information

```shell
Apple Swift version 5.9-dev (LLVM d07bd3c51da387d, Swift 02812e86abc52c2)
Target: arm64-apple-macosx13.0
```

**Comment by d-ronnqvist** [comment]
There's probably some overlap here with https://github.com/apple/swift-docc/issues/553 (Clearly indicate when a build resulted in no pages)

**Comment by d-ronnqvist** [comment]
Actually, after re-reading the description of this issue. This is the same issue as https://github.com/apple/swift-docc/issues/553.
