### ISSUE TITLE
Links to same-page section that start with "#" fail.

### ISSUE THREAD

**Issue by d-ronnqvist** [apple/swift-docc#632]
### Description

It's possible to link to headings (although not topic sections, but that's unrelated) by adding a # and a heading name to the documentation link. For example, `<doc:ArticleName#HeadingName>`. 

For links to headings on the same page it's possible to omit the article name (or symbol name) and only write  `<doc:HeadingName>`. However, adding the leading # causes the link to fail  `<doc:#HeadingName>`. 

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Both  `<doc:HeadingName>` and  `<doc:#HeadingName>` should link work for linking to a heading on the current page.

### Actual behavior

`<doc:#HeadingName>` result in an error about "" (empty string) not being found at the current page.

### Steps To Reproduce

In a project with a documentation catalog; add an article with some heading and write a link to that heading on the same page. For example

```md
# Some article

An article with a heading that it also links to: <doc:#Something>

## Something
```

### Swift-DocC Version Information

5.9

### Swift Compiler Version Information

```shell
swift-driver version: 1.85 Apple Swift version 5.9 (swiftlang-5.9.0.118.1 clang-1500.0.32.1)
Target: arm64-apple-macosx14.0
```

**Comment by d-ronnqvist** [comment]
This is probably a good first issue for anyone wanting to familiarize themselves with how DocC resolves documentation links. 

The issue probably exist in `static PathHierarchy.parse(path:omittingEmptyComponents:)` or in how the parsed path is used.

Don't hesitate to ping me if you want to work on this and have any questions.

**Comment by natikgadzhi** [comment]
@d-ronnqvist, I'm just getting started around here, but I would love to work on this. Expect some rough draft on Wednesday night PST

**Comment by d-ronnqvist** [comment]
Feel free to ask questions if you’re wondering how something works or why something is done the way it is.

**Comment by natikgadzhi** [comment]
Got it to work, but I'm not entirely sure about side effects. I'll make a pull request for this, and another one with a little documentation addition, and ask a bunch of questions. Huge thank you for being so supportive of beginners! <3
