### ISSUE TITLE
Valid choices and meaning for `--level` undocumented.

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-docc#689]
### Description

The `--experimental-documentation-coverage` and `--level` flags *appear* to have no effect, but either way they should be documented or removed.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

**Comment by d-ronnqvist** [comment]
Also, it doesn't look like the default behavior in Swift Argument Parser prints the allowed values as part of the help text but it is printed in the error message. So if you pass `--level=something` to `docc convert` then you'll get this error message
```
Error: The value 'something' is invalid for '--level <level>'. Please provide one of 'none', 'brief' or 'detailed'.
```

**Comment by dabrahams** [comment]
Something should indicate that this prints coverage as part of the build process and doesn't embed the coverage in the generated HTML like e.g. Jazzy does.

**Comment by d-ronnqvist** [comment]
> Something should indicate that this prints coverage as part of the build process and doesn't embed the coverage in the generated HTML like e.g. Jazzy does.

Agreed. It also writes a "documentation-coverage.json" file within the archive which should also be mentioned.

**Comment by d-ronnqvist** [comment]
Also, it's redundant to have both a boolean `--experimental-documentation-coverage` and to have `none` be the default value for `--level`. Those could be combined into a single option.
