### ISSUE TITLE
Non-deterministic failures without diagnostic

### ISSUE THREAD

**Issue by dabrahams** [apple/swift-docc#697]
### Description

I get one of these errors every so often when running docc:

```
error: 'docc convert' invocation failed with a nonzero exit code: '6'
error: 'docc convert' invocation failed with a nonzero exit code: '11'
error: 'docc convert' invocation failed with a nonzero exit code: '64'
```

The command I'm using is:

```
        set -eo pipefail
        for TARGET in CLI Driver FrontEnd Core IR CodeGenLLVM Utils TestUtils HyloModule GenerateHyloFileTests; do
          mkdir -p _site/docc/"$TARGET"
          swift package --allow-writing-to-directory ./_site \
          generate-documentation \
          --target "$TARGET" \
          --output-path _site/docc/"$TARGET" \
          --experimental-documentation-coverage --level brief \
          --enable-inherited-docs \
          --transform-for-static-hosting \
          --hosting-base-path Hylo/docc/"$TARGET"
        done
```

I'm using it on [this project](https://github.com/hylo-lang/hyloc).  An example is [here](https://github.com/hylo-lang/hyloc/actions/runs/5885007273/job/15960726865?pr=836#step:9:622).

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Successful completion always.

### Steps To Reproduce

With [this project](https://github.com/hylo-lang/hyloc), follow the README instructions for building, and then run the command I gave in my description.

### Swift-DocC Version Information

Whatever is installed with Xcode 14.3.1 I presume

### Swift Compiler Version Information

```shell
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

**Comment by dabrahams** [comment]
I think this was my problem, not docc's.  Will open a new one if that turns out to be wrong.  Sorry for the bad report!

**Comment by dabrahams** [comment]
I guess I was mistaken about being mistaken :(.  Still [happening](https://github.com/hylo-lang/hyloc/actions/runs/5898031028/job/15998481394#step:10:620).

**Comment by d-ronnqvist** [comment]
Is it always the same target that fails? Both examples look like the same "exit code: '6'" failure for the Core target. 

To avoid needing to install and configure LLVM; would it be possible to attach a zip of the symbol graph files from that target (or all of the targets)? You can see the file path of the symbol graph files if you pass `--verbose` to the `generate-documentation` command.

**Comment by dabrahams** [comment]
> Is it always the same target that fails? Both examples look like the same "exit code: '6'" failure for the Core target.

I didn't notice, sorry.  

>  would it be possible to attach a zip of the symbol graph files

Voila: [extracted-symbols.zip](https://github.com/apple/swift-docc/files/12411201/extracted-symbols.zip)

**Comment by d-ronnqvist** [comment]
The crash that I could reproduce is caused by a concurrency issue with the experimental documentation coverage feature. I think that could explain why the errors only occur sometimes and why the exit code isn't always the same.
