### ISSUE TITLE
Can't reference forward-slash operator functions

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-docc#714]
### Description

I'm attempting to write DocC documentation for [CasePaths](https://github.com/pointfreeco/swift-case-paths), which uses a prefix `/` operator for defining a "case" path from an enum type to a particular case (similar to how `\` is used for defining a key path). While I can document these operator functions, I cannot refer to them or organize them:

1. Xcode lists autocompletion for these functions, but autocompletes result in invalid DocC references, _e.g._ ``/(embed:)`` (`/` doesn't seem to be a valid identifier, and the function is overloaded many times).
2. If I run the DocC server and manually navigate to these functions, I get URLs like http://localhost:8080/documentation/casepaths/(_:)-82yvm, but none of the following work when trying to reference the function in documentation:

    - `(_:)-82yvm`
    - `/(_:)-82yvm`
    - `_(_:)-82yvm`
    - `\/(_:)-82yvm`
    - `%2F(_:)-82yvm`
    - `%2f(_:)-82yvm`

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I expect there to be a way to reference and organize these APIs.

### Actual behavior

I cannot find a way to reference or organize these APIs.

### Steps To Reproduce

1. Define a `prefix operator /` and function that uses it.
2. Attempt to reference the function in documentation.
3. Build documentation.

### Swift-DocC Version Information

SwiftDocCPlugin 1.3.0

### Swift Compiler Version Information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
```

**Comment by stephencelis** [comment]
Additionally, the library defines a `..` infix operator, and I can't figure out how to reference it, either.

**Comment by d-ronnqvist** [comment]
The issue with the forwards slash characters is a recently discovered that's issue also tracked as rdar://112555102.

> Additionally, the library defines a `..` infix operator, and I can't figure out how to reference it, either.
> 
I _think_ that the `..` infix operator would be linked to using `..(_:_:)`. 

DocC inserts a leading `'` to any path component that start with "..". That said, I would think `'..(_:_:)` would be close enough to `..(_:_:)` for DocC to be able to diagnose and suggest a fixit for it. What diagnostic message are you getting for the `'..(_:_:)` link?

**Comment by stephencelis** [comment]
> I _think_ that the `..` infix operator would be linked to using `..(_:_:)`.

That worked, thanks!

> DocC inserts a leading `'` to any path component that start with "..". That said, I would think `'..(_:_:)` would be close enough to `..(_:_:)` for DocC to be able to diagnose and suggest a fixit for it. What diagnostic message are you getting for the `'..(_:_:)` link?

Unfortunately, Xcode autocompleted `..(lhs:rhs:)` instead, and no suggestions were offered.

**Comment by d-ronnqvist** [comment]
https://github.com/apple/swift-docc/pull/717 should resolve the issue with forward slash operators functions.


> Unfortunately, Xcode autocompleted `..(lhs:rhs:)` instead, and no suggestions were offered. When I manually tried `'..(_:_:)` no suggestions were offered, either. When I entered `..(_:_:)` I _was_ finally given suggestions since `..` is overloaded a couple times.

The root cause of the autocompletion issue isn't in DocC's code so that'd have to be tracked with a Radar or Feedback. 

`..(lhs:rhs:)` seems to be too different from `..(_:_:)` to be offered as a suggestion but `'..(_:_:)` is close enough to be offered as a suggestion in Xcode 15.0 (15A240d)

<img width="890" alt="Screenshot 2023-09-26 at 1 11 48 PM" src="https://github.com/apple/swift-docc/assets/1228143/f5d145ae-9c8b-4a05-bbc1-d6e84479c406">

**Comment by stephencelis** [comment]
> The root cause of the autocompletion issue isn't in DocC's code so that'd have to be tracked with a Radar or Feedback.

@d-ronnqvist Thanks! Did you open a feedback?

**Comment by d-ronnqvist** [comment]
> > The root cause of the autocompletion issue isn't in DocC's code so that'd have to be tracked with a Radar or Feedback.
> 
> @d-ronnqvist Thanks! Did you open a feedback?

I didn't but after searching I can say that rdar://78412414 is tracking this specific autocomplete issue.
