### ISSUE TITLE
Xcode "Build documentation" not working with Swift Macro package in project

### ISSUE THREAD

**Issue by irisha8787** [apple/swift-docc#849]
### Description

fatal error: module map file 

`Intermediates.noindex/GeneratedModuleMaps-iphonesimulator/SwiftSyntaxMacros.modulemap' not found`
when building documentation for a project with a dependency on SwiftMacro in Xcode 15.2 or Xcode 15.3

It seems like there are more swift syntax package module map files are missing from the  GeneratedModuleMaps-iphonesimulator folder, when comparing to GeneratedModuleMaps folder.

**Comment by kimdv** [comment]
I've also filed an issue: FB13548539

**Comment by d-ronnqvist** [comment]
Issues about Xcode is strictly out of scope for this repo. This will be tracked using the mentioned radar and feedback instead.

**Comment by irisha8787** [comment]
@kimdv @ahoppen is there a link I can follow for tracking?

**Comment by ahoppen** [comment]
I don’t think there will be a GitHub issue tracking this since this needs to be fixed in Xcode, which is not open source. @d-ronnqvist Please correct me if I’m wrong.

**Comment by ashton-seek** [comment]
I found a workaround to use until Xcode fixes this. A build phase script that runs first can simply create empty modulemap files for the ones that are missing.

```bash
#!/bin/bash
# This script creates stub modulemap files for missing modules that docbuild requires.

# skip if not building documentation
if [ "$ACTION" != "docbuild" ]; then
    exit 0
fi

# Known modules
modules=(
    "SwiftSyntaxMacros"
    "SwiftSyntax509"
    "SwiftSyntax"
    "SwiftDiagnostics"
    "SwiftParser"
    "SwiftBasicFormat"
    "SwiftParserDiagnostics"
    "SwiftSyntaxBuilder"
    "SwiftCompilerPlugin"
    "SwiftOperators"
    "SwiftSyntaxMacroExpansion"
    "SwiftCompilerPluginMessageHandling"
)

if [ ! -d "$GENERATED_MODULEMAP_DIR" ]; then
    echo "Creating base directory: $GENERATED_MODULEMAP_DIR"
    mkdir -p "$GENERATED_MODULEMAP_DIR"
fi

# Create stub modulemap files for any missing in the list
echo "Creating stub module maps in $GENERATED_MODULEMAP_DIR..."
for module in "${modules[@]}"; do
    module_map_file="${GENERATED_MODULEMAP_DIR}/${module}.modulemap"
    
    if [ ! -f "$module_map_file" ]; then
        echo "${module} - Creating stub modulemap"
        touch "$module_map_file"
    else
        echo "${module} - modulemap already exists."
    fi
done

echo "Done creating missing module map files"
```

I had to put this build phase above the Headers phase. I tried using script dependencies but I could not get that to work with docbuild.

**Comment by moshe-foreflight** [comment]
Is this still an issue with prebuilts and SwiftSyntax support for prebuilts?
