### ISSUE TITLE
This mangled quote/code fence results in a crash

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift-docc#930]
### Description

Through a combination of typos and copy-pasta I ended up with this monstrousity. It crashes the docc tool that is installed with Xcode 15.3

```
# Title

> ```warning: passing argument of non-sendable type 'Style' into main actor-isolated context may introduce data races`  
> `       await updateUI(with: style)`  
> `                      ^`  
> `note: class 'Style' does not conform to the 'Sendable' protocol` ```
```

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

I would definitely expect some kind of error.

### Steps To Reproduce

I input the following into a standalone `.md` file in my .docc bundle and ran the following command:

`xcrun docc convert --experimental-enable-custom-templates --output-path ./my-docs Docs.docc`

### Swift Compiler Version Information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by d-ronnqvist** [comment]
This is a #678 which was fixed by #840 in February. This fix is available on "main" and the "6.0" release branch.
